# Generated by Django 5.0.5 on 2024-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_submission_allow_view_score_submission_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
