# Generated by Django 5.0.5 on 2024-06-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_assignment_id_submission_assignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='is_submitted',
            new_name='is_submited',
        ),
    ]
