# Generated by Django 5.0.5 on 2024-06-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_is_submitted_submission_is_submited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='is_submited',
            new_name='is_submitted',
        ),
    ]
