# Generated by Django 5.0.5 on 2024-06-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_is_submited_submission_is_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assignment',
            new_name='assignment_id',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='is_submitted',
            new_name='is_submited',
        ),
    ]
