# Generated by Django 5.0.5 on 2024-12-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rename_assignment_id_submission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='414c49434527532041', max_length=200),
        ),
    ]
