# Generated by Django 5.0.5 on 2024-12-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_assignment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
