# Generated by Django 5.0.5 on 2024-12-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_assignment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
